# Generated by Django 5.0.1 on 2026-02-23 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_default_restaurant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Restaurant owner account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_restaurants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
