# Generated by Django 5.0.1 on 2026-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="combo_selections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected combo choices for this item",
            ),
        ),
    ]
