# Generated by Django 5.0.1 on 2026-04-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_deviceprofile_passcode_hash"),
        ("orders", "0003_add_combo_selections_to_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Tablet/device that placed this order (null for non-device orders)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="devices.deviceprofile",
            ),
        ),
    ]
