# Generated by Django 5.0.1 on 2025-12-21 13:52

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this configuration", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one configuration can be active at a time",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Odoo server URL (e.g., http://localhost:10018)",
                        max_length=255,
                    ),
                ),
                (
                    "database",
                    models.CharField(help_text="Odoo database name", max_length=100),
                ),
                (
                    "username",
                    models.CharField(help_text="Odoo username (email)", max_length=100),
                ),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Odoo password (encrypted)"
                    ),
                ),
                (
                    "pos_config_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Selected Odoo POS configuration ID",
                        null=True,
                    ),
                ),
                (
                    "pos_config_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the selected POS configuration",
                        max_length=100,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=300,
                        help_text="Request timeout in seconds",
                        validators=[django.core.validators.MinValueValidator(10)],
                    ),
                ),
                (
                    "retry_attempts",
                    models.IntegerField(
                        default=3,
                        help_text="Number of retry attempts for failed requests",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "auto_sync_orders",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically sync orders to Odoo when confirmed",
                    ),
                ),
                (
                    "sync_menu_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable nightly menu synchronization from Odoo",
                    ),
                ),
                (
                    "sync_tables_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable nightly table synchronization from Odoo",
                    ),
                ),
                (
                    "last_test_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time connection was tested",
                        null=True,
                    ),
                ),
                (
                    "last_test_success",
                    models.BooleanField(
                        default=False, help_text="Result of last connection test"
                    ),
                ),
                (
                    "last_test_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message from last failed connection test",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Odoo Configuration",
                "verbose_name_plural": "Odoo Configurations",
                "ordering": ["-is_active", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="odoo_integr_is_acti_f98cc8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OdooSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("ORDER_PUSH", "Order Push"),
                            ("MENU_SYNC", "Menu Sync"),
                            ("TABLE_SYNC", "Table Sync"),
                            ("MANUAL_RETRY", "Manual Retry"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "odoo_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of created/updated record in Odoo",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sync failed"
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full error traceback for debugging"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of retry attempts",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of retry attempts",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When to retry this sync (for exponential backoff)",
                        null=True,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Request data sent to Odoo"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Response data received from Odoo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When sync completed (success or final failure)",
                        null=True,
                    ),
                ),
                (
                    "odoo_config",
                    models.ForeignKey(
                        help_text="Odoo configuration used for this sync",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="odoo_integration.odooconfig",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Order being synced (for ORDER_PUSH type)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odoo_sync_logs",
                        to="orders.order",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this sync (null for automatic syncs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_odoo_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Odoo Sync Log",
                "verbose_name_plural": "Odoo Sync Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sync_type", "status"],
                        name="odoo_integr_sync_ty_c98dc5_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="odoo_integr_order_i_7a4584_idx",
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="odoo_integr_status_3e6b2c_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="odoo_integr_created_d38075_idx"
                    ),
                ],
            },
        ),
    ]
