# Generated by Django 5.0.1 on 2026-04-09 16:32

import devices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0004_menuitem_is_combo_menuitemcombochoice"),
        ("odoo_integration", "0001_initial"),
        ("restaurants", "0004_alter_restaurant_odoo_config_fk"),
        ("tables", "0003_table_restaurant_alter_table_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label, e.g. 'Table 5 Tablet'",
                        max_length=100,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        default=devices.models.generate_device_id,
                        help_text="Auto-generated short code shown on login screen",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "passcode_hash",
                    models.CharField(
                        help_text="Argon2-hashed 4-6 digit PIN", max_length=128
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict visible categories (empty = show all)",
                        related_name="devices",
                        to="menu.category",
                    ),
                ),
                (
                    "odoo_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override restaurant-level Odoo config (leave blank to inherit)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="odoo_integration.odooconfig",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        help_text="Table this device is fixed to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Profile",
                "verbose_name_plural": "Device Profiles",
                "ordering": ["restaurant", "name"],
                "indexes": [
                    models.Index(
                        fields=["device_id"], name="devices_dev_device__ee5286_idx"
                    ),
                    models.Index(
                        fields=["restaurant", "is_active"],
                        name="devices_dev_restaur_507bc7_idx",
                    ),
                ],
            },
        ),
    ]
