# Generated by Django 5.0.1 on 2026-04-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceprofile",
            name="passcode_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy — unused since login switched to device_id + table_number.",
                max_length=128,
            ),
        ),
    ]
