# Generated by Django 5.0.1 on 2025-11-08 20:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Table number or identifier (e.g., 'T1', 'A-5')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Maximum number of people",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("INDOOR", "Indoor"),
                            ("OUTDOOR", "Outdoor"),
                            ("VIP", "VIP"),
                            ("BAR", "Bar"),
                        ],
                        default="INDOOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("CLEANING", "Cleaning"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="table_qr_codes/"
                    ),
                ),
                (
                    "qr_code_data",
                    models.CharField(
                        blank=True,
                        help_text="URL or data encoded in QR code",
                        max_length=255,
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(
                        default=1,
                        help_text="Floor number",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether table is active and available for use",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Special notes about this table (e.g., near window, accessible)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["section", "number"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"],
                        name="tables_tabl_status_2cc868_idx",
                    ),
                    models.Index(
                        fields=["section"], name="tables_tabl_section_688c1f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TableSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_count",
                    models.IntegerField(
                        help_text="Number of customers at the table",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When customers were seated",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customers checked out (null if still active)",
                        null=True,
                    ),
                ),
                (
                    "session_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this session (e.g., special occasion)",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Customer rating (1-5)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="Customer feedback"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary customer/account holder for this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Session",
                "verbose_name_plural": "Table Sessions",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["table", "end_time"],
                        name="tables_tabl_table_i_875228_idx",
                    ),
                    models.Index(
                        fields=["start_time"], name="tables_tabl_start_t_ee7e78_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WaiterAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this assignment starts",
                    ),
                ),
                (
                    "shift_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this assignment ends (null if still active)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this assignment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiter_assignments",
                        to="tables.table",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        limit_choices_to={"role": "WAITER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiter Assignment",
                "verbose_name_plural": "Waiter Assignments",
                "ordering": ["-shift_start"],
                "indexes": [
                    models.Index(
                        fields=["waiter", "shift_end"],
                        name="tables_wait_waiter__473d78_idx",
                    ),
                    models.Index(
                        fields=["table", "shift_end"],
                        name="tables_wait_table_i_84cdbe_idx",
                    ),
                ],
            },
        ),
    ]
