# Generated by Django 5.0.1 on 2025-12-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="odoo_floor_id",
            field=models.IntegerField(
                blank=True, help_text="Odoo restaurant floor ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="odoo_last_synced",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this table was synced from Odoo",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="odoo_table_id",
            field=models.IntegerField(
                blank=True, help_text="Odoo restaurant table ID", null=True, unique=True
            ),
        ),
    ]
