# Generated by Django 5.0.1 on 2025-12-21 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="odoo_category_id",
            field=models.IntegerField(
                blank=True, help_text="Odoo product category ID", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="odoo_last_synced",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this category was synced from Odoo",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="odoo_last_synced",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this item was synced from Odoo",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MenuItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu_items/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Mark as primary/thumbnail image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Image",
                "verbose_name_plural": "Menu Item Images",
                "ordering": ["menu_item", "order", "-is_primary"],
                "indexes": [
                    models.Index(
                        fields=["menu_item", "is_primary"],
                        name="menu_menuit_menu_it_465904_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MenuItemReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="Admin can hide inappropriate reviews"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Review",
                "verbose_name_plural": "Menu Item Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["menu_item", "is_approved"],
                        name="menu_menuit_menu_it_cfddd3_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="menu_menuit_rating_3b840e_idx"
                    ),
                ],
                "unique_together": {("menu_item", "user")},
            },
        ),
    ]
